---
title: "NBA tests"
author: "EA"
date: "11/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##

```{r}
df <- read.csv("../dunkest.csv", sep = ";")
names(df)
```

```{r}
library(tidyverse)
df %>% select("Team") %>% table
```

```{r}
n_days <- 5
min_days <- 3

big_df <- df %>%
  filter(Day > (max(.$Day) - n_days)) %>% 
  group_by(Player, Team) %>%
  summarize(Team = tail(Team, 1),
            Pos = tail(Pos, 1),
            PDK_mean = mean(PDK),
            PDK_sd = sd(PDK),
            PDK_last = tail(PDK, 1),
            PDK_n = n(),
            CR = tail(CR, 1),
            PDK_CR = PDK_mean / CR,
            PLUS = tail(PLUS, 1),
            PCT_GAIN = PLUS/CR * 100,
            ) %>%
  filter(PDK_n >= min_days,
         PDK_n <= n_days) %>% 
  arrange(desc(PDK_CR)) %>% 
  mutate_if(is.numeric, round, 2)

n_g <- 4
n_f <- 4
n_c <- 2

g <- big_df %>%
  filter(Pos == "G") %>%
  head(n_g)

f <- big_df %>%
  filter(Pos == "F") %>%
  head(n_f)

c <- big_df %>%
  filter(Pos == "C") %>%
  head(n_c)

rbind(g,f,c)
```


```{r}
df <- read.csv("dunkest.csv", sep = ";")
n_days <- 5
min_days <- 3
n_g <- 4
n_f <- 4
n_c <- 2
optimize <- "PDK_CR"
asc = T

big_df <- df %>%
    filter(Day > (max(.$Day) - n_days)) %>% 
    group_by(Player, Team) %>%
    summarize(Team = tail(Team, 1),
              Pos = tail(Pos, 1),
              PDK_mean = mean(PDK),
              PDK_sd = sd(PDK),
              PDK_last = tail(PDK, 1),
              PDK_n = n(),
              CR = tail(CR, 1),
              PDK_CR = PDK_mean / CR,
              PLUS = tail(PLUS, 1),
              PCT_GAIN = PLUS/CR * 100,
    ) %>%
    filter(PDK_n >= min_days,
           PDK_n <= n_days) %>% 
    mutate_if(is.numeric, round, 2)

big_df <- if (asc) {
    big_df %>% 
        arrange(optimize)
} else {
    big_df %>% 
        arrange(desc(optimize))
}

g <- big_df %>%
    filter(Pos == "G") %>%
    head(n_g)

f <- big_df %>%
    filter(Pos == "F") %>%
    head(n_f)

c <- big_df %>%
    filter(Pos == "C") %>%
    head(n_c)

rbind(g,f,c)

```





